### ISSUE TITLE
Implementing a feature from Docusaurus - Full Markdown Support

### ISSUE THREAD

**Issue by saminarp** [saminarp/rwar#13]
This week I am implementing one cool feature from Docusaurus for rwar SSG.  

### Inspiration 
- [x] Check out Docusaurus's features 
- [x] Build a site with Docusaurus and experiment with it

### Tasks for full MD support in rwar 

- [x] Implement the full markdown support feature 
- [x] Use the markdown2 library 
- [x] Test, test, test 
- [x] Deploy 
- [x] File issues for subsequent releases
